version: '2'
catalog:
  name: "alpine"
  version: "v3.7"
  description: "Lightweight container instances for testing"
  minimum_rancher_version: v1.2.0
  questions:
    - variable: alpine_image
      description: "The docker image to use for the testing container."
      label: "Container Image"
      type: "enum"
      options:
        - "dockerguys/alpine:3.6"
        - "dockerguys/alpine:3.7"
        - "alpine:3.6"
        - "alpine:3.7"
      default: "dockerguys/alpine:3.7"
      required: true
    - variable: volume_name
      description: "Name of volume to mount. Ignore if not mounting an external volume."
      label: "External Volume"
      type: "string"
      required: false
    - variable: volume_driver
      label: "Volume Driver"
      description: "Driver to use for volume. Ignore if not mounting an external volume."
      type: "enum"
      options:
        - local
        - rancher-nfs
      required: true
      default: "local"
    - variable: volume_mountpoint
      description: "Path to mount volume. Ignore if not mounting an external volume."
      label: "Volume Mountpoint"
      type: "string"
      required: true
      default: "/var/lib/storage"
    - variable: repull_image
      description: "Pull from registry source even if the host already have a local image with the same tag."
      label: "Reload Images"
      type: enum
      options:
        - always
        - never
      required: true
      default: "never"
    - variable: docker_registry_name
      description: "Pull from private registry. Leave blank to pull from public Docker Hub."
      label: "Private Registry"
      type: "string"
      required: false
    - variable: host_affinity_label
      description: "The container will launch on one of the hosts that has this label."
      label: "Host Affinity Label"
      type: "string"
      required: false
services:
  alpine:
    scale: 1
