name: Windows Activation
description: |
  Windows activation server
version: v0.1112
category: Windows
maintainer: Dockerguys <dockerguys@lizoc.com>
license: Proprietary ULA
projectURL: https://code.lizoc.com/dockerguys/alpines
