.catalog:
  name: "mysql"
  version: "v10.1.26.0"
  description: "A recommended stack for the MySQL RDBMS."
  minimum_rancher_version: v1.0.0
  questions:
    - variable: mysql_lb_port
      description: "Public port for access to MySQL through the load balancer"
      label: "MySQL Public LB Port"
      required: true
      default: 3306
      type: "int"
    - variable: mysql_root_name
      description: "The name of the root superuser account. The root superuser account will have full access to all databases."
      label: "MySQL Root User"
      required: true
      type: "string"
      default: "root"
    - variable: mysql_root_password
      description: "The password that will be set for the MySQL root superuser account."
      label: "MySQL Root Password"
      required: true
      type: password
    - variable: mysql_image
      description: "The docker image to use for the MySQL server."
      label: "MySQL Docker Image"
      type: "enum"
      options:
        - "dockerguys/mariadb:10.1.26.0"
      default: "dockerguys/mariadb:10.1.26.0"
      required: true
    - variable: mysql_database
      description: "Specify the name of a database to be created on image startup."
      label: "MySQL Database"
      required: true
      type: "string"
      default: "DefaultDB"
    - variable: mysql_user
      description: "Creates an additional MySQL (super)user. MySQL Password must also be set."
      label: "MySQL User"
      required: true
      type: "string"
      default: "dbadmin"
    - variable: mysql_password
      description: "A password for the additional MySQL (super)user. MySQL User must also be set."
      label: "MySQL Password"
      required: true
      type: password
    - variable: mysql_extargs
      description: "Extra arguments for starting up 'mysqld'. Do not specify the 'user' or 'console' flags."
      label: "MySQL Startup Arguments"
      type: "string"
      default: ""
      required: false

version: '2'
services:
  mysql-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: tcp
        service: mysql
        source_port: ${mysql_lb_port}
        target_port: 3306
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  mysql:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 3306
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  mysql-data:
    scale: 1
    start_on_create: true
