version: '2'
catalog:
  name: "Gitea"
  version: "v1.3"
  description: "A lightweight GitHub clone"
  minimum_rancher_version: v0.51.0
  maintainer: dockerguys <dockerguys@lizoc.com>
  questions:
    - variable: "gitea_image"
      label: "Gitea Image"
      description: "Image to use"
      required: true
      default: "gitea/gitea:1.4"
      type: enum
      options: # List of options if using type of `enum`
        - gitea/gitea:1.4
        - gitea/gitea:1.3.3
        - gitea/gitea:latest
        - dockerguys/gitea:1.4
    - variable: "db_service"
      description: "External DB service to use. You can reference the service as 'db' by setting this."
      label: "DB Service"
      default: ""
      required: true
      type: "service"
    - variable: host_affinity_label
      description: "The stack will launch on one of the hosts that has this label."
      label: "Host Affinity Label"
      type: "string"
      required: false
    - variable: docker_registry_name
      description: "Pull from private registry. Leave blank to pull from public Docker Hub."
      label: "Private Registry"
      type: "string"
      required: false
services:
  gitea:
    scale: 1
    retain_ip: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 3000
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 120000
