version: '2'
catalog:
  name: "CoreDNS"
  version: "1.6"
  description: "DNS and Service Discovery"
  questions:
    - variable: coredns_image
      description: "CoreDNS server image"
      label: "CoreDNS Image"
      type: enum
      options:
        - dockerguys/coredns:1.6
        - dockerguys/coredns:latest
      required: true
      default: "dockerguys/coredns:1.6"
    - variable: coredns_upstream_forward
      description: "Profile to use for upstream DNS server"
      label: "Upstream Server"
      type: enum
      options:
        - cloudflare-tls
        - quad9-tls
        - china
      required: true
      default: "cloudflare-tls"
    - variable: coredns_port
      description: "Port to listen for DNS requests. The host will open this UDP port directly, unless UDP is disabled."
      label: "DNS Port"
      type: int
      required: true
      default: 53
    - variable: coredns_disable_udp
      description: "Disable UDP port. You need to configure the load balancer manually."
      label: "Disable UDP"
      type: boolean
      required: true
      default: false
    - variable: coredns_private_domains
      description: "Domains that should not be resolved by upstream DNS server. Separate by space."
      label: "Private Domains"
      type: string
      required: true
      default: "internal"
    - variable: coredns_internal_upstream_server
      description: "IP address of your LAN DNS server for resolving local domains."
      label: "Internal Upstream DNS"
      type: string
      required: false
    - variable: coredns_internal_upstream_domain
      description: "Domain to be resolved by your LAN DNS server."
      label: "Internal Upstream Domain"
      type: string
      required: true
      default: "internal"
    - variable: coredns_enable_metrics
      description: "Enable metrics reporting"
      label: "Enable Metrics"
      type: boolean
      required: true
      default: true
    - variable: coredns_brand_name
      description: "Customize the DNS server response for CH TXT server information"
      label: "Brand Name"
      type: string
      required: true
      default: "CoreDNS-1"
    - variable: coredns_brand_author
      description: "Customize the DNS server response for CH TXT author information"
      label: "Brand Author"
      type: string
      required: true
      default: "websecurity@lizoc.com"
    - variable: coredns_lb_label
      description: "The label on hosts that are scheduled to run the loadbalancer stack"
      label: "Loadbalancer Label"
      type: string
      required: true
      default: "io.role.loadbalancer"
    - variable: coredns_lb_stack
      description: "Name of the stack that is running the target loadbalancers"
      label: "Loadbalancer Stack"
      type: string
      required: true
      default: "loadbalancer"
    # --- common param: host affinity
    - variable: host_affinity_label
      description: "The stack will launch on one of the hosts that has this label."
      label: "Host Affinity Label"
      type: string
      required: false
    # --- common param: repull
    - variable: repull_image
      description: "Pull from registry source even if the host already have a local image with the same tag."
      label: "Reload Images"
      type: enum
      options:
        - always
        - never
      required: true
      default: "never"
    # --- common param: custom registry
    - variable: docker_registry_name
      description: "Pull from private registry. Leave blank to pull from public Docker Hub."
      label: "Private Registry"
      type: string
      required: false
    # --- common param: limit memory; exclude docker_memory_swap_limit
    - variable: docker_memory_limit
      label: "Limit Memory"
      description: "Maxiumum memory that each container can use (in megabytes). Defaults to unlimited. Do not specify a value lower than 4."
      type: int
      required: false
    - variable: docker_memory_kernel_limit
      label: "Limit Kernel Memory"
      description: |
        Maxiumum kernel memory that each container can use (in megabytes). Defaults to unlimited. If this value is lower than Limit Memory, 
        the container will experience OOM error if it runs out of kernel memory, unless memory is unlimited, in which case it will wait 
        for memory released.
      type: int
      required: false
    # --- common param: limit cpu
    - variable: docker_cpu_quota_limit
      label: "Limit CPUs"
      description: |
        Limit CPU resources (in multiples of 100,000 microseconds). Defaults to unlimited. For example, "150000" limits the container 
        to 1.5 CPUs.
      type: int
      required: false
    - variable: docker_cpu_weight_limit
      label: "CPU Weight"
      description: |
        A number lower than the default will have less priority when competing for CPU resources and vice verse.
      type: int
      required: true
      default: 1024

services:
  coredns:
    scale: 1
    health_check:
      request_line: GET /health HTTP/1.0
      port: 8080
      response_timeout: 2000
      healthy_threshold: 2
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 120000
