version: '2'
catalog:
  name: "CoreDNS"
  version: "1.8"
  description: "DNS and Service Discovery"
  questions:
    - variable: coredns_image
      description: "CoreDNS server image"
      label: "CoreDNS Image"
      type: enum
      options:
        - dockerguys/coredns:1.8
      required: true
      default: "dockerguys/coredns:1.8"
    - variable: coredns_port
      description: "Port to listen for DNS requests. The host will open this UDP port directly, unless UDP is disabled."
      label: "DNS Port"
      type: int
      required: true
      default: 53
    - variable: coredns_expose_udp_port
      description: "Expose UDP DNS port on host directly. You need a UDP load-balancer if this is false."
      label: "Expose DNS Port"
      type: boolean
      required: true
      default: true
    - variable: coredns_enable_metrics
      description: "Enable metrics reporting"
      label: "Enable Metrics"
      type: boolean
      required: true
      default: true
    - variable: coredns_enable_zones
      description: "Enable serving zone files"
      label: "Enable Zones"
      type: boolean
      required: true
      default: false
    - variable: coredns_ratelimit_maxquery
      description: "Throttle maximum concurrent queries. 0 means disable rate limiting."
      label: "Rate Limit"
      type: int
      required: true
      default: 0
    - variable: coredns_ipindn_domain
      description: "IP-in-Domain-Name encode IP inside domain name. Leave blank to disable."
      label: "IP-in-DN Zone"
      type: string
      required: false
    - variable: coredns_brand_name
      description: "Customize the DNS server response for CH TXT server information"
      label: "Brand Name"
      type: string
      required: true
      default: "CoreDNS-1"
    - variable: coredns_brand_author
      description: "Customize the DNS server response for CH TXT author information"
      label: "Brand Author"
      type: string
      required: true
      default: "websecurity@lizoc.com"
    - variable: coredns_upstream_forward
      description: "Profile to use for upstream DNS server"
      label: "Upstream Server"
      type: enum
      options:
        - cloudflare-tls
        - google-tls
        - quad9-tls
        - alidns-tls
      required: true
      default: "cloudflare-tls"
    - variable: coredns_upstream_expiry
      description: "Number of seconds to cache upstream results"
      label: "Upstream Cache TTL"
      type: int
      required: true
      default: 30
    - variable: coredns_upstream_policy
      description: "Loadbalance policy for upstream DNS server"
      label: "Upstream Policy"
      type: string
      required: true
      options:
        - random
        - round_robin
        - quad9-tls
      default: random
    - variable: coredns_private_domains
      description: "Domains that should not be resolved by upstream DNS server. Separate by space."
      label: "Private Domains"
      type: string
      required: true
      default: "internal"
    - variable: coredns_internal_upstream_server
      description: "IP address(es) of your LAN DNS server for resolving local domains. Separate by space."
      label: "Internal Upstream DNS"
      type: string
      required: false
    - variable: coredns_internal_upstream_domain
      description: "Domain(s) to be resolved by your LAN DNS servers."
      label: "Internal Upstream Domain"
      type: string
      required: true
      default: "internal"
    - variable: coredns_console_log
      description: "Write log to standard output. If false, writes to /var/log/coredns."
      label: "Console Log"
      type: boolean
      required: true
      default: true
    # --- common param: host affinity
    - variable: host_affinity_label
      description: "The stack will launch on one of the hosts that has this label."
      label: "Host Affinity Label"
      type: string
      required: false
    # --- common param: storage; subst vols_required = `volume ("Volume Name"_[zones,static])`
    - variable: datavolume_name
      label: "Volume Base Name"
      description: |
        To store the application data in volume(s), enter the base volume name that should be used. One or more volumes will be created with this value as the prefix. 
        By default, all volumes created will be host scoped named. See "Storage Driver" for other storage options.
      required: false
      type: string
    - variable: volume_exists
      label: "Volume Exists"
      description: |
        Check this if you have already created the volume ("Volume Name"_[zones,static]). Remember to set the "Volume Storage Driver" too. Do not fill 
        in "NFS Driver Host" or "NFS Driver Volume Path".
      required: true
      type: boolean
      default: false
    #- variable: storage_size
    #  label: "Volume Storage Size"
    #  description: "Limit the size of the log volume (in megabytes). Defaults to unlimited."
    #  required: false
    #  type: int
    - variable: storage_driver
      label: "Volume Storage Driver"
      description: |
        To use a stack scoped volume backed by a persistent storage service, enter the name
        of an existing storage driver (e.g. "rancher-nfs"). This also requires "Volume Name" to be set.
      required: true
      type: enum
      default: "local"
      options:
        - local
        - rancher-nfs
    - variable: storage_driver_nfsopts_host
      label: "NFS Driver Host"
      description: |
        Specify a NFS hostname instead of the default NFS server. Only fill in this option if "Volume Storage Driver" is 
        set to "rancher-nfs", and the volume does not already exist.
      required: false
      type: string
    - variable: storage_driver_nfsopts_export
      label: "NFS Driver Volume Path"
      description: |
        Specify the exported base path on the NFS server (e.g. "/storage/nfsvol"). The full directory(ies) created 
        on the NFS server will be this path and the volume name(s). Do not append the "/" at the end. This exported base path 
        must already exist on the NFS server. Only fill in this option if "Volume Storage Driver" is set to "rancher-nfs", and 
        the volume does not already exist.
      required: false
      type: string
    - variable: storage_retain_volume
      label: "Retain NFS Volume"
      description: Keep the volumes created even after this stack gets deleted. This option has no effect if the volume(s) already exists.
      required: true
      type: boolean
      value: false
    # --- common param: repull
    - variable: repull_image
      description: "Pull from registry source even if the host already have a local image with the same tag."
      label: "Reload Images"
      type: enum
      options:
        - always
        - never
      required: true
      default: "never"
    # --- common param: custom registry
    - variable: docker_registry_name
      description: "Pull from private registry. Leave blank to pull from public Docker Hub."
      label: "Private Registry"
      type: string
      required: false
    # --- common param: limit memory; exclude docker_memory_swap_limit
    - variable: docker_memory_limit
      label: "Limit Memory"
      description: "Maxiumum memory that each container can use (in megabytes). Defaults to unlimited. Do not specify a value lower than 4."
      type: int
      required: false
    - variable: docker_memory_kernel_limit
      label: "Limit Kernel Memory"
      description: |
        Maxiumum kernel memory that each container can use (in megabytes). Defaults to unlimited. If this value is lower than Limit Memory, 
        the container will experience OOM error if it runs out of kernel memory, unless memory is unlimited, in which case it will wait 
        for memory released.
      type: int
      required: false
    # --- common param: limit cpu
    - variable: docker_cpu_quota_limit
      label: "Limit CPUs"
      description: |
        Limit CPU resources (in multiples of 100,000 microseconds). Defaults to unlimited. For example, "150000" limits the container 
        to 1.5 CPUs.
      type: int
      required: false
    - variable: docker_cpu_weight_limit
      label: "CPU Weight"
      description: |
        A number lower than the default will have less priority when competing for CPU resources and vice verse.
      type: int
      required: true
      default: 1024

services:
  coredns:
    scale: 1
    health_check:
      request_line: GET /health HTTP/1.0
      port: 8080
      response_timeout: 2000
      healthy_threshold: 2
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 120000
