name: Alpine
description: |
    Simple lightweight containers used for testing
version: v3.6
category: DevOps
maintainer: Dockerguys <dockerguys@lizoc.com>
license: Proprietary ULA
projectURL: https://code.lizoc.com/dockerguys/alpines
