version: '2'
catalog:
  name: "Taiga"
  version: "v1.0.0"
  description: "Love your projects"
  minimum_rancher_version: v0.51.0
  questions:
    - variable: "taiga_secret"
      label: "Taiga Secret"
      description: "Secret for default user, database, etc."
      required: true
      default: "ChangeMeChangeMe"
      type: "password"
    - variable: "taiga_domain"
      label: "Domain FQDN"
      description: "Domain where Taiga is hosted"
      required: true
      type: "string"
      default: "taiga"
    - variable: "ssl_enabled"
      label: "SSL Terminated"
      description: "Enable if the endpoints will be SSL terminated"
      required: true
      type: "boolean"
      default: false
    - variable: "taiga_debug_mode"
      label: "Debug Mode"
      description: "Enable debug mode"
      required: true
      type: "boolean"
      default: false
    - variable: "taiga_enable_register"
      label: "Enable Public Registration"
      description: "Enable self service registration"
      required: true
      type: "boolean"
      default: false
    - variable: "taiga_enable_gravatar"
      label: "Enable Gravatar"
      description: "Gravatar is an external service for avatars"
      required: true
      type: "boolean"
      default: false
    - variable: "taiga_support_url"
      label: "Support URL"
      description: "Customize support link URL"
      required: true
      type: "string"
      default: "https://www.lizoc.com/support/teamworks"
    - variable: "taiga_terms_url"
      label: "Terms URL"
      description: "Customize terms and conditions link URL"
      required: true
      type: "string"
      default: "https://www.lizoc.com/terms"
    - variable: "taiga_privacy_url"
      label: "Privacy URL"
      description: "Customize privacy statement link URL"
      required: true
      type: "string"
      default: "https://www.lizoc.com/privacy"
    - variable: redis_cache_size_mb
      label: "Cache Limit Memory"
      description: "Maxiumum memory that Redis container can use (in megabytes)."
      type: int
      required: true
      default: 256
    - variable: "taiga_backend_image"
      label: "Taiga Backend Image"
      description: "Backend image name."
      required: true
      default: "dockerguys/taiga:5.0"
      type: "enum"
      options:
        - "dockerguys/taiga:5.0"
    - variable: "taiga_frontend_image"
      label: "Taiga Frontend Image"
      description: "Frontend image name."
      required: true
      default: "dockerguys/taiga:5.0-web"
      type: "enum"
      options:
        - "dockerguys/taiga:5.0-web"
    - variable: "taiga_events_image"
      label: "Taiga Events Image"
      description: "Events server image name."
      required: true
      default: "dockerguys/taiga:5.0-events"
      type: "enum"
      options:
        - "dockerguys/taiga:5.0-events"
    - variable: "pgsql_image"
      label: "PostgreSQL Image"
      description: "PostgreSQL is required for backend database."
      required: true
      default: "dockerguys/postgres:12.2"
      type: "enum"
      options:
        - "dockerguys/postgres:12.2"
    - variable: "redis_image"
      label: "Redis Image"
      description: "Redis is used to cache data for performance."
      required: true
      default: "dockerguys/redis:5.0"
      type: "enum"
      options:
        - "dockerguys/redis:5.0"
    #
    # rabbitmq
    #
    # --- common param: host affinity
    - variable: host_affinity_label
      description: "The stack will launch on one of the hosts that has this label."
      label: "Host Affinity Label"
      type: string
      required: false
    # --- common param: storage; subst vols_required = `volume ("Volume Name"_[conf,media])`
    - variable: datavolume_name
      label: "Volume Base Name"
      description: |
        To store the application data in volume(s), enter the base volume name that should be used. One or more volumes will be created with this value as the prefix. 
        By default, all volumes created will be host scoped named. See "Storage Driver" for other storage options.
      required: false
      type: string
    - variable: volume_exists
      label: "Volume Exists"
      description: |
        Check this if you have already created the volume ("Volume Name"_[conf,media]). Remember to set the "Volume Storage Driver" too. Do not fill 
        in "NFS Driver Host" or "NFS Driver Volume Path".
      required: true
      type: boolean
      default: false
    #- variable: storage_size
    #  label: "Volume Storage Size"
    #  description: "Limit the size of the log volume (in megabytes). Defaults to unlimited."
    #  required: false
    #  type: int
    - variable: storage_driver
      label: "Volume Storage Driver"
      description: |
        To use a stack scoped volume backed by a persistent storage service, enter the name
        of an existing storage driver (e.g. "rancher-nfs"). This also requires "Volume Name" to be set.
      required: true
      type: enum
      default: "local"
      options:
        - local
        - rancher-nfs
    - variable: storage_driver_nfsopts_host
      label: "NFS Driver Host"
      description: |
        Specify a NFS hostname instead of the default NFS server. Only fill in this option if "Volume Storage Driver" is 
        set to "rancher-nfs", and the volume does not already exist.
      required: false
      type: string
    - variable: storage_driver_nfsopts_export
      label: "NFS Driver Volume Path"
      description: |
        Specify the exported base path on the NFS server (e.g. "/storage/nfsvol"). The full directory(ies) created 
        on the NFS server will be this path and the volume name(s). Do not append the "/" at the end. This exported base path 
        must already exist on the NFS server. Only fill in this option if "Volume Storage Driver" is set to "rancher-nfs", and 
        the volume does not already exist.
      required: false
      type: string
    - variable: storage_retain_volume
      label: "Retain NFS Volume"
      description: Keep the volumes created even after this stack gets deleted. This option has no effect if the volume(s) already exists.
      required: true
      type: boolean
      value: false
    # --- common param: repull
    - variable: repull_image
      description: "Pull from registry source even if the host already have a local image with the same tag."
      label: "Reload Images"
      type: enum
      options:
        - always
        - never
      required: true
      default: "never"
    # --- common param: custom registry
    - variable: docker_registry_name
      description: "Pull from private registry. Leave blank to pull from public Docker Hub."
      label: "Private Registry"
      type: string
      required: false
    # --- common param: limit memory
    - variable: docker_memory_limit
      label: "Limit Memory"
      description: "Maxiumum memory that each container can use (in megabytes). Defaults to unlimited. Do not specify a value lower than 4."
      type: int
      required: false
    - variable: docker_memory_kernel_limit
      label: "Limit Kernel Memory"
      description: |
        Maxiumum kernel memory that each container can use (in megabytes). Defaults to unlimited. If this value is lower than Limit Memory, 
        the container will experience OOM error if it runs out of kernel memory, unless memory is unlimited, in which case it will wait 
        for memory released.
      type: int
      required: false
    - variable: docker_memory_swap_limit
      label: "Limit Swap Memory"
      description: |
        Maxiumum swap that each container can use (in megabytes). Defaults to twice of memory limit. Set to "-1" to allow unlimited, 
        or the same value as Limit Memory to disable swap.
      type: int
      required: false
    # --- common param: limit cpu
    - variable: docker_cpu_quota_limit
      label: "Limit CPUs"
      description: |
        Limit CPU resources (in multiples of 100,000 microseconds). Defaults to unlimited. For example, "150000" limits the container 
        to 1.5 CPUs.
      type: int
      required: false
    - variable: docker_cpu_weight_limit
      label: "CPU Weight"
      description: |
        A number lower than the default will have less priority when competing for CPU resources and vice verse.
      type: int
      required: true
      default: 1024

services:
  lbs:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: /events
        priority: 1
        protocol: http
        service: events
        source_port: 80
        target_port: 8888
      - path: /api
        priority: 2
        protocol: http
        service: taiga
        source_port: 80
        target_port: 80
      - path: /admin
        priority: 3
        protocol: http
        service: taiga
        source_port: 80
        target_port: 80
      - path: /static
        priority: 4
        protocol: http
        service: taiga
        source_port: 80
        target_port: 80
      - path: /media
        priority: 5
        protocol: http
        service: taiga
        source_port: 80
        target_port: 80
      - priority: 6
        protocol: http
        service: tgfront
        source_port: 80
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  taiga:
    scale: 1
    retain_ip: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 120000
      request_line: GET "/api/v1/" "HTTP/1.0"
  tgfront:
    scale: 1
    retain_ip: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 120000
      request_line: GET "/" "HTTP/1.0"
  events:
    scale: 1
    retain_ip: true
