version: '2'
catalog:
  name: "Keycloak"
  version: "3.4.3"
  description: "Self-hosted single sign-on solution"
  questions:
    - variable: keycloak_user
      description: "Primary administrative user"
      label: "Admin User"
      type: "string"
      required: true
      default: administrator
    - variable: keycloak_password
      description: "Password for primary administrative user"
      label: "Admin Password"
      type: "password"
      required: true
      default: ChangeMeChangeMe
    - variable: db_vendor
      description: "Use embedded h2 for testing purposes only. Otherwise you need to set up postgres and mysql/mariadb first."
      label: "Database Vendor"
      type: enum
      options:
        - postgres
        - mysql
        - mariadb
        - h2
      required: true
      default: h2
    - variable: "keycloak_image"
      label: "Keycloak Image"
      description: "Image to use"
      required: true
      default: "dockerguys/keycloak:3.4.3"
      type: enum
      options: # List of options if using type of `enum`
        - jboss/keycloak:latest
        - jboss/keycloak:3.4.3.Final
        - dockerguys/keycloak:3.4.3
        - dockerguys/keycloak:3.4.3-mk2
    - variable: "db_service"
      description: "External DB service to use (if 'Database Vendor' is not 'h2'). You can reference the service as 'db' by setting this."
      label: "DB Service"
      default: ""
      required: false
      type: "service"
    - variable: keycloak_dbname
      description: "Name of database to use. Ignore this if 'Database Vendor' is h2."
      label: "Database Name"
      type: "string"
      required: true
      default: "keycloak"
    - variable: keycloak_dbuser
      description: "Username to login to the database. Ignore this if 'Database Vendor' is h2."
      label: "Database Username"
      type: "string"
      required: true
      default: "keycloakapp"
    - variable: keycloak_dbpassword
      description: "User password to login to the database. Ignore this if 'Database Vendor' is h2."
      label: "Database Password"
      type: "password"
      required: true
      default: "DatabasePassword"
    - variable: keycloak_extarg
      description: "Additional startup arguments to '/opt/jboss/keycloak/bin/standalone.sh'. Use '--server-config=standalone-ha.xml' for cluster mode. Check official documentation at 'https://docs.jboss.org/author/display/WFLY8/Command+line+parameters' for details."
      label: "Startup Arguments"
      type: "string"
      required: true
      default: "-b=0.0.0.0 -Dkeycloak.profile.feature.docker=enabled --server-config=standalone-ha.xml"
    - variable: datavolume_name
      label: Volume Name
      description: |
        To store the application data in a volume, enter the volume name that should be used.
        By default this will be a (host scoped) named Docker volume. Set "Storage Driver" other storage options.
      required: false
      type: string
    - variable: storage_driver
      label: Volume Storage Driver
      description: |
        To use a stack scoped volume backed by a persistent storage service, enter the name
        of an existing storage driver (e.g. rancher-nfs). This also requires "Volume Name" to be set.
      required: false
      type: string
    - variable: storage_driver_opts
      label: Storage Driver Option
      description: |
        Specify a single "driver_opts" key/value pair in the format "optionName: optionValue".
        E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 1".
      required: false
      type: string
    - variable: host_affinity_label
      description: "The stack will launch on one of the hosts that has this label."
      label: "Host Affinity Label"
      type: "string"
      required: false
    - variable: repull_image
      description: "Pull from registry source even if the host already have a local image with the same tag."
      label: "Reload Images"
      type: enum
      options:
        - always
        - never
      required: true
      default: "never"
    - variable: docker_registry_name
      description: "Pull from private registry. Leave blank to pull from public Docker Hub."
      label: "Private Registry"
      type: "string"
      required: false
services:
  keycloak:
    scale: 1
    retain_ip: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 120000
