name: WordPress
description: |
  Blog Tool, Publishing Platform, and CMS
version: 1.0.0
category: Web
maintainer: Dockerguys <dockerguys@lizoc.com>
license: Proprietary ULA
projectURL: https://code.lizoc.com/dockerguys/library
