version: '2'
catalog:
  name: "Webserver"
  version: "v1.0.0"
  description: "A webserver for static files"
  minimum_rancher_version: v0.51.0
  maintainer: dockerguys <dockerguys@lizoc.com>
  questions:
    - variable: "nginx_image"
      label: "NginX Image"
      description: "Image to use. Be sure to fill in the 'Private Registry' field too if the image is not available publically."
      required: true
      default: "dockerguys/nginx:1.14.0"
      type: enum
      options: # List of options if using type of `enum`
        - dockerguys/nginx:1.14.0
    - variable: host_affinity_label
      description: "The stack will launch on one of the hosts that has this label."
      label: "Host Affinity Label"
      type: "string"
      required: false
    - variable: datavolume_name
      label: Volume Name
      description: |
        To store the application data in a volume, enter the volume name that should be used.
        By default this will be a (host scoped) named Docker volume. Set "Storage Driver" other storage options.
      required: false
      type: string
    - variable: storage_driver
      label: Volume Storage Driver
      description: |
        To use a stack scoped volume backed by a persistent storage service, enter the name
        of an existing storage driver (e.g. rancher-nfs). This also requires "Volume Name" to be set.
      required: true
      type: "enum"
      default: "local"
      options:
        - local
        - rancher-nfs
    - variable: storage_exists
      label: Volume Exists
      description: |
        Check this if you have already created the volume. Do not fill in 'NFS Driver Host' and 'NFS Driver Volume Path'.
      required: true
      type: boolean
      default: false
    - variable: storage_driver_nfsopts_host
      label: NFS Driver Host
      description: |
        Specify a NFS hostname instead of the default NFS server. Only use this option if "Volume Storage Driver" is 
        set to "rancher-nfs".
      required: false
      type: string
    - variable: storage_driver_nfsopts_export
      label: NFS Driver Volume Path
      description: |
        Specify the path on the NFS server that will be mounted (e.g. "/storage/nfsvol"). The full directory created 
        on the NFS server will be this path and the volume name. Do not append the "/" at the end. The full path must 
        already exist on the NFS server. Only use this option if "Volume Storage Driver" is set to "rancher-nfs".
      required: false
      type: string
    - variable: repull_image
      description: "Pull from registry source even if the host already have a local image with the same tag."
      label: "Reload Images"
      type: enum
      options:
        - always
        - never
      required: true
      default: "never"
    - variable: docker_registry_name
      description: "Pull from private registry. Leave blank to pull from public Docker Hub."
      label: "Private Registry"
      type: "string"
      required: false
services:
  nginx:
    scale: 1
    retain_ip: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 120000
