version: '2'
catalog:
  name: "V2Ray Server"
  version: "4.0"
  description: "Internet communication obfuscation server"
  questions:
    - variable: v2ray_image
      description: "V2Ray core server image"
      label: "V2Ray Image"
      type: enum
      options:
        - dockerguys/v2ray:4.20.0
      required: true
      default: "dockerguys/v2ray:4.20.0"
    - variable: "v2ray_image_custom"
      label: "Custom V2Ray server image"
      description: "Use a custom V2Ray image. This will override value of V2Ray image."
      required: false
      type: string
    - variable: "v2ray_default_client_guid"
      label: "Default Client GUID"
      description: "Specify the default client GUID. Leave blank to generate automatically."
      required: false
      type: string
    # --- common param: host affinity
    - variable: host_affinity_label
      description: "The stack will launch on one of the hosts that has this label."
      label: "Host Affinity Label"
      type: string
      required: false
    # --- common param: repull
    - variable: repull_image
      description: "Pull from registry source even if the host already have a local image with the same tag."
      label: "Reload Images"
      type: enum
      options:
        - always
        - never
      required: true
      default: "never"
    # --- common param: custom registry
    - variable: docker_registry_name
      description: "Pull from private registry. Leave blank to pull from public Docker Hub."
      label: "Private Registry"
      type: string
      required: false
    # --- common param: limit memory; exclude docker_memory_swap_limit
    - variable: docker_memory_limit
      label: "Limit Memory"
      description: "Maxiumum memory that each container can use (in megabytes). Defaults to unlimited. Do not specify a value lower than 4."
      type: int
      required: false
    - variable: docker_memory_kernel_limit
      label: "Limit Kernel Memory"
      description: |
        Maxiumum kernel memory that each container can use (in megabytes). Defaults to unlimited. If this value is lower than Limit Memory, 
        the container will experience OOM error if it runs out of kernel memory, unless memory is unlimited, in which case it will wait 
        for memory released.
      type: int
      required: false
    # --- common param: limit cpu
    - variable: docker_cpu_quota_limit
      label: "Limit CPUs"
      description: |
        Limit CPU resources (in multiples of 100,000 microseconds). Defaults to unlimited. For example, "150000" limits the container 
        to 1.5 CPUs.
      type: int
      required: false
    - variable: docker_cpu_weight_limit
      label: "CPU Weight"
      description: |
        A number lower than the default will have less priority when competing for CPU resources and vice verse.
      type: int
      required: true
      default: 1024

services:
  v2ray:
    scale: 1
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 1080
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 120000
