name: OSTicket
description: |
  Most Popular Customer Support Software
version: 1.0.0
category: CRM
maintainer: Dockerguys <dockerguys@lizoc.com>
license: Proprietary ULA
projectURL: https://code.lizoc.com/dockerguys/alpines
