name: Shadowsocks Server
description: |
  Active traffic obfuscation using SOCKS5 based proxy.
version: 3.2.5
category: Networking
maintainer: Dockerguys <dockerguys@lizoc.com>
license: Proprietary ULA
projectURL: https://code.lizoc.com/dockerguys/alpines
