name: Gitea
description: |
  Lightweight alternative to GitHub
version: v1.7.5
category: Git
maintainer: Dockerguys <dockerguys@lizoc.com>
license: Proprietary ULA
projectURL: https://code.lizoc.com/dockerguys/alpines
