version: '2'
catalog:
  name: "nfsvol-migrate"
  version: "v3.7"
  description: "Migrate a volume to a remote NFS server"
  minimum_rancher_version: v1.2.0
  questions:
    - variable: migrate_image
      description: "The migratrator docker image."
      label: "Migrator Image"
      type: "enum"
      options:
        - "dockerguys/alpine:3.11"
      default: "dockerguys/alpine:3.11"
      required: true
    - variable: volume_driver
      label: "Volume Storage Driver"
      description: |
        To use a stack scoped volume backed by a persistent storage service, enter the name
        of an existing storage driver (e.g. "rancher-nfs").
      required: true
      type: enum
      default: "local"
      options:
        - local
        - rancher-nfs
    - variable: volume1_name
      description: "Name of volume to mount. Volume must exists on source and destination."
      label: "Volume 1 Name"
      type: "string"
      required: true
    - variable: volume2_name
      description: "Name of volume to mount. Volume must exists on source and destination. Ignore if not migrating multiple volumes"
      label: "Volume 2 Name"
      type: "string"
      required: false
    - variable: volume3_name
      description: "Name of volume to mount. Volume must exists on source and destination. Ignore if not migrating multiple volumes"
      label: "Volume 3 Name"
      type: "string"
      required: false
    - variable: volume4_name
      description: "Name of volume to mount. Volume must exists on source and destination. Ignore if not migrating multiple volumes"
      label: "Volume 4 Name"
      type: "string"
      required: false
    - variable: volume5_name
      description: "Name of volume to mount. Volume must exists on source and destination. Ignore if not migrating multiple volumes"
      label: "Volume 5 Name"
      type: "string"
      required: false
    - variable: volume6_name
      description: "Name of volume to mount. Volume must exists on source and destination. Ignore if not migrating multiple volumes"
      label: "Volume 6 Name"
      type: "string"
      required: false
    - variable: remote_nfs_host
      label: "Remote NFS Host"
      description: |
        Specify a NFS hostname that is reachable by this container.
      required: true
      type: string
    - variable: remote_nfs_export_base
      label: "Remote NFS Base Path"
      description: |
        Specify the exported base path on the NFS server (e.g. "/storage/hdd/nfsvol"). Do not append the "/" at the end. This 
        exported path must already exist on the NFS server.
      required: true
      type: string
    # --- common param: host affinity
    - variable: host_affinity_label
      description: "The stack will launch on one of the hosts that has this label."
      label: "Host Affinity Label"
      type: string
      required: false
    # --- common param: repull
    - variable: repull_image
      description: "Pull from registry source even if the host already have a local image with the same tag."
      label: "Reload Images"
      type: enum
      options:
        - always
        - never
      required: true
      default: "never"
    # --- common param: custom registry
    - variable: docker_registry_name
      description: "Pull from private registry. Leave blank to pull from public Docker Hub."
      label: "Private Registry"
      type: string
      required: false
    # --- common param: limit memory
    - variable: docker_memory_limit
      label: "Limit Memory"
      description: "Maxiumum memory that each container can use (in megabytes). Defaults to unlimited. Do not specify a value lower than 4."
      type: int
      required: false
    - variable: docker_memory_kernel_limit
      label: "Limit Kernel Memory"
      description: |
        Maxiumum kernel memory that each container can use (in megabytes). Defaults to unlimited. If this value is lower than Limit Memory, 
        the container will experience OOM error if it runs out of kernel memory, unless memory is unlimited, in which case it will wait 
        for memory released.
      type: int
      required: false
    - variable: docker_memory_swap_limit
      label: "Limit Swap Memory"
      description: |
        Maxiumum swap that each container can use (in megabytes). Defaults to twice of memory limit. Set to "-1" to allow unlimited, 
        or the same value as Limit Memory to disable swap.
      type: int
      required: false
    # --- common param: limit cpu
    - variable: docker_cpu_quota_limit
      label: "Limit CPUs"
      description: |
        Limit CPU resources (in multiples of 100,000 microseconds). Defaults to unlimited. For example, "150000" limits the container 
        to 1.5 CPUs.
      type: int
      required: false
    - variable: docker_cpu_weight_limit
      label: "CPU Weight"
      description: |
        A number lower than the default will have less priority when competing for CPU resources and vice verse.
      type: int
      required: true
      default: 1024

services:
  nfsmigrator:
    scale: 1
