name: NATS
description: |
  Connect edge and distributed systems
category: Communication
version: v1.0.0
maintainer: Dockerguys <dockerguys@lizoc.com>
license: Proprietary ULA
projectURL: https://code.lizoc.com/dockerguys/library
